### basic settings

# site properties and page defaults
title: Hands-On Astronomy
subtitle: Organizing Committee of the Ecuadorian Olympiads on Astronomy and Astrophysics
description: Workshops, courses and opportunities for instructors.
logo-text: false
header: images/background.jpg
footer: images/background.jpg
header-dark: false
footer-dark: false
proofer: false

# site social media and other links
links:
  email: info@oeaa-astro.org
  instagram: oeaa_ec

### Jekyll settings to ignore
